- include_tasks: uninstall.yml
  when: django_uninstall

- block:
  - import_tasks: system.yml

  # Database
  - name: Verify that we have a valid django_dbtype
    fail:
      msg: "django_dbtype must be either 'postgres' or 'mariadb'"
    when: "django_dbtype not in ['postgres', 'mariadb']"

  - import_tasks: postgres.yml
    when: django_dbtype == 'postgres'

  - import_tasks: mariadb.yml
    when: django_dbtype == 'mariadb'

  - set_fact:
      is_database_empty: "{{ postgres_db_empty_check.changed or mariadb_db_empty_check.changed }}"

  - import_tasks: django.yml

  - import_tasks: wsgi.yml
    when: django_create_uwsgi_config

  - import_tasks: nginx.yml
    when: django_create_uwsgi_config

  when: not django_uninstall
