---
- name: Ensure that uWSGI is installed
  apt: name={{ item }} state=latest
  with_items:
    - uwsgi
    - uwsgi-plugin-python
    - uwsgi-plugin-python3

- name: Create uWSGI config
  template: src=uwsgi.ini dest={{ django_path }}/uwsgi.ini
  register: wsgi_config
  notify:
    - nginx restart

- name: Setup systemd service
  template:
    src: uwsgi_systemd
    dest: "/etc/systemd/system/{{ django_name }}-wsgi.service"
    owner: root
    group: root
    mode: 0644
  register: wsgi_service
  notify:
    - nginx restart

- name: Reload systemd because we've just updated a service
  shell: systemctl daemon-reload
  when: wsgi_service|changed

- name: Ensure that the wsgi service is enabled
  service: "name={{ django_name }}-wsgi enabled=yes"

# We can't use a handler for this, because handlers don't work well with dynamic parameters.
- name: Restart uWSGI service
  service: "name={{ django_name }}-wsgi state=restarted"
  when: wsgi_service.changed or wsgi_config.changed or src_sync_changed or django_needs_restart
